### ISSUE TITLE
Cart View details missing

### ISSUE THREAD

**Issue by Arjun-sna** [Codebrahma/CB-node-serverless#66]
Current cart view doesn't have any detail on the price of the items. It shows only the quantity of each item.
![screenshot-localhost-3000-2018 05 25-11-54-41](https://user-images.githubusercontent.com/9337254/40529443-7a112e80-6012-11e8-90c1-d6f8305ad128.png)

**Comment by kaushiknishchay** [comment]
<img width="1233" alt="screen shot 2018-05-26 at 10 29 49 pm" src="https://user-images.githubusercontent.com/15786884/40578611-6725e5e0-6134-11e8-9c2d-2b2a526117e8.png">
New PR with info pushed
